name: CI-master

on:
    push:
        branches: [master]
env:
    DOCKER_NAME: github-raw-backend
    DOCKER_IMAGE: ghcr.io/heavyrisem/github-raw-backend
    VERSION: ${{ github.sha }}

jobs:
    test:
        name: Jest
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup Node.js environment
              uses: actions/setup-node@v2.5.1
              with:
                  node-version: 17

            - name: install dependencies
              run: yarn install

            - name: initialize environments
              run: |
                  echo 'GIT_REPOS=${{ secrets.GIT_REPOS }}' >> .env
                  echo GIT_WEBHOOK_SECRET=${{ secrets.GIT_WEBHOOK_SECRET }} >> .env
                  echo GIT_ROOT=${{ secrets.GIT_ROOT }} >> .env

            - name: Jest Unit test
              run: yarn test
