name: Deploy

on:
  # 하단 코드에 따라 develop 브랜치에 Push 또는 Pull Request 이벤트가 발생한 경우에 Workflow가 실행됩니다.
  # 만약 브랜치 구분 없이 이벤트를 지정하고 싶을 경우에는 단순히 아래와 같이 작성도 가능합니다.
  # on: [push, pull_request]
  	push:
    	branches: [develop]
	pull_request:
    	branches: [develop]

  # 해당 옵션을 통해 사용자가 직접 Actions 탭에서 Workflow를 실행시킬 수 있습니다.
  # 여기에서는 추가적으로 더 설명하지는 않겠습니다.
  workflow_dispatch:

jobs:

    build:

        name: Build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master
            
            - name: send custom message with args
			uses: appleboy/discord-action@master
			with:
				webhook_id: ${{ secrets.WEBHOOK_ID }}
				webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
				args: The ${{ github.event_name }} event triggered first step.